In [2]:
import pandas as pd
import numpy as np

## creating one dimensional pandas series

In [4]:
series = pd.Series([1,4,np.NaN,7])
series

0    1.0
1    4.0
2    NaN
3    7.0
dtype: float64

## Creating Pandas dataframe using dict

In [7]:
data =  [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
...     {'a': 100, 'b': 200, 'c': 300, 'd': 400},
...     {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000 }]

s = pd.Series(data)
df = pd.DataFrame(data)
print("Series") 
print(s)
print()
print("Dataframe")
print(df)

Series
0                {'a': 1, 'b': 2, 'c': 3, 'd': 4}
1        {'a': 100, 'b': 200, 'c': 300, 'd': 400}
2    {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000}
dtype: object

Dataframe
      a     b     c     d
0     1     2     3     4
1   100   200   300   400
2  1000  2000  3000  4000


## Series Operations

In [12]:
print(series,"\n")
print("mean: ",series.mean(),"\n")
print("mode: ",series.mode(),"\n")
print("value_count: ",series.value_counts(),"\n")
print("count: ",series.count(),"\n")
print("std: ",series.std(),"\n")
print("min: ",series.min(),"\n")
print("max: ",series.max(),"\n")
print("iloc: ",series.iloc[0],"\n")
print(series.describe())



0    1.0
1    4.0
2    NaN
3    7.0
dtype: float64 

mean:  4.0 

mode:  0    1.0
1    4.0
2    7.0
dtype: float64 

value_count:  1.0    1
4.0    1
7.0    1
Name: count, dtype: int64 

count:  3 

std:  3.0 

min:  1.0 

max:  7.0 

iloc:  1.0 

count    3.0
mean     4.0
std      3.0
min      1.0
25%      2.5
50%      4.0
75%      5.5
max      7.0
dtype: float64


In [8]:
shape = (3,3)
zeroes = np.zeros(shape, int)
print(zeroes)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [9]:
ones = np.ones(shape, float)
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
nparray = np.random.randint(0,5,(6,6))
print(nparray)

[[4 0 0 2 3 1]
 [3 0 3 0 0 4]
 [2 2 4 3 1 2]
 [0 1 3 2 0 1]
 [2 0 0 3 2 1]
 [0 2 3 1 3 1]]


In [11]:
dataset = pd.read_csv("../Datasets/AAPL.csv")
print(dataset, '\n')
print(dataset[['Date', 'High']])
print(dataset['Close'])
print(dataset[(dataset['Low']>=130) &(dataset['High'] == 133)])

         Date  Open  High  Low  Close  Adj Close    Volume
0  2023-01-09   130   133  129    130        129  70790800
1  2023-01-10   130   131  128    130        130  63896200
2  2023-01-11   131   133  130    133        132  69458900
3  2023-01-12   133   134  131    133        132  71379600 

         Date  High
0  2023-01-09   133
1  2023-01-10   131
2  2023-01-11   133
3  2023-01-12   134
0    130
1    130
2    133
3    133
Name: Close, dtype: int64
         Date  Open  High  Low  Close  Adj Close    Volume
2  2023-01-11   131   133  130    133        132  69458900


In [12]:
student_data = [[1,15],[2,11],[3,11],[4,20]]

In [13]:
df1 = pd.DataFrame(data=student_data, columns=['student_id','age'], index=['oje',4,5,6], dtype=int)
df1

student_id  age
oje           1   15
4             2   11
5             3   11
6             4   20

In [14]:
df.head(3)

a     b     c     d
0     1     2     3     4
1   100   200   300   400
2  1000  2000  3000  4000

In [15]:
my_dict = {'student_id':[101,52,128,3], 'name':['Ulysses','William',None,'Henry'], 'age':[13,10,6,13]}

df = pd.DataFrame(my_dict)

result = df[['name','age']][df['student_id']==101]
result

name  age
0  Ulysses   13

In [16]:
hi = df['age']
print(hi)
hello = [x*2 for x in hi]
print(hello)
df['bonus'] = hello
df
# df.drop_duplicates(subset=['age'], keep='first')


0    13
1    10
2     6
3    13
Name: age, dtype: int64
[26, 20, 12, 26]


student_id     name  age  bonus
0         101  Ulysses   13     26
1          52  William   10     20
2         128     None    6     12
3           3    Henry   13     26

In [17]:
df2 = pd.DataFrame(np.arange(12).reshape(3, 4),columns=['A', 'B', 'C', 'D'])
df2

A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [18]:

# df.fillna(0)
# df.bfill()
df.dropna(subset=['name'])
df

student_id     name  age  bonus
0         101  Ulysses   13     26
1          52  William   10     20
2         128     None    6     12
3           3    Henry   13     26

In [19]:
# df['student_id'] = [x*2 for x in df['student_id']]


# df.columns = ['hu','ha','hi']
# df
# df['age'] = df['age'].astype(dtype=int)
# df.dtypes

In [20]:
df['age'] = np.NAN
df
df['age'] = df['age'].fillna(0)
df


student_id     name  age  bonus
0         101  Ulysses  0.0     26
1          52  William  0.0     20
2         128     None  0.0     12
3           3    Henry  0.0     26